//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int SituationId { get; set; }
        public string PeopleGroup { get; set; }
        public string Action { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Situation Situation { get; set; }
    }
}
